project:
  name: quickstart-microsoft-dotnetcore-cicd
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - eu-west-1
  - us-east-1
  - us-east-2
  - us-west-2
tests:
  dotnet:
    parameters:
      GitHubRepositoryName: quickstart-dotnet-serverless-cicd
      GitHubBranchName: develop
      GitHubOwner: aws-quickstart
      GitHubOAuthToken: github-token
      CodeBuildImage: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      SolutionStack: 64bit Amazon Linux 2 v2.0.1 running .NET Core
    regions:
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-2
    template: templates/quickstart-dotnetcore-cicd.template.yaml
